trigger:
- master
- dev/*

jobs:
  - job: 'Windows'
    timeoutInMinutes: 300 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 10 # how much time to give 'run always even if cancelled tasks' before stopping them
    pool:
      vmImage: 'windows-latest'
    variables:
      VCPKG_DEFAULT_TRIPLET: "x64-windows"
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(System.DefaultWorkingDirectory)/build.ps1'
        arguments: '-DoNotUpdateTOOL -DisableInteractive -DisableLaTeX'
      displayName: 'Build FEMM'
    - powershell: |
        makensis.exe $(System.DefaultWorkingDirectory)/script.nsi
      displayName: Build Installer
    - task: CopyFiles@2
      inputs:
        contents: '$(System.DefaultWorkingDirectory)/FEMM_installer.exe'
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)/FEMM_installer.exe
        artifactName: FEMM_installer
