trigger:
  branches:
    include:
      - "*"       # We trigger on all branches

jobs:
  - job: 'Build_Windows'
    pool:
      vmImage: 'windows-latest'
    variables:
      GIT_REDIRECT_STDERR: "2>&1"
    steps:
      - task: PowerShell@2
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/build.ps1'
      - task: CopyFiles@2
        inputs:
          contents: '$(System.DefaultWorkingDirectory)/bin/**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: FEMM-IPI
